management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
  otlp:
    metrics:
      export:
        enabled: false

logging:
  level:
    com.vmware.tanzu.demos: DEBUG
